if True:
  print("This is always printed")

if False:
  print("This is never printed")







#Generated by AI replit
x = 5
if x > 3:
    print("x is greater than 3")

x = 10
if x < 0:
    print("x is negative")
elif x == 0:
    print("x is zero")
else:
    print("x is positive")